feat: Calculate Gross Properties
fib-international/structuralcodes pull request #103
Opened 2024-06-10 12:13 UTC by talledodiego

Draft implementation for computation of gross section properties.

2024-06-11 13:56 UTC, talledodiego commented
@mortenengen I am asking your review here.

Points to discuss:
I computed area moments basing only on areas A, Sy, Sz, Iyy, Izz, Iyz (not accounting for different E of materials) and I have computed the same multiplied by their E (EA, ESy, ESz, EIyy, EIzz, EIyz). 
It's user's responsibility understanding if the former make sense to him.

We could also implement a `transform_gross_properties(E_ref)` method that return A, Sy, Sz, Iyy, Izz, Iyz etc. dividing each EA, ESy etc. by a reference value of E `E_ref` passed to the function. In this way we could obtain the homogenized values with elastic modulus of user choice (e.g. elastic modulus of concrete). 

Further topic: in computation of gross properties I have considered both SurfaceGeometry and PointGeometry (so I am accounting the effect of reinforcement bars). Is it ok or do we want just concrete (or better said just SurfaceGeometry)?
Finally, during computation of point geometry effects we are not cleaning the missing concrete. The error is generally small. Should we do it?

2024-06-13 05:33 UTC, mortenengen commented on structuralcodes/geometry/_geometry.py
> +        density: t.Optional[float] = None,
Should we perhaps specify that the value of density is only used if material is `ConstitutiveLaw`?

2024-06-13 05:37 UTC, mortenengen commented on structuralcodes/geometry/_geometry.py
> +            new_material = Elastic(E=geo.material.get_tangent(eps=0)[0])
This behaviour of creating a linear elastic material with the initial tangent as stiffness should be documented in the docstring.

2024-06-13 05:37 UTC, mortenengen commented on structuralcodes/geometry/_geometry.py
> +        """Create a new PointGeometry with a different material."""
Please add a docstring.

2024-06-13 05:40 UTC, mortenengen commented on structuralcodes/geometry/_geometry.py
> +        """Create a new CompoundGeometry with a different material."""
Please describe the args and kwargs in the docstring.

2024-06-13 05:53 UTC, mortenengen commented on structuralcodes/sections/_generic.py
> +        # and mass: Morten -> problem with units! how do we deal with it?
Good question. We specify in docstrings that the density should be given in kg/m3, but we are not specifying any unit for the geometry. I think it is ok for now, but we should do a more thorough review of all connected parts of the code before v0.0.1.

2024-06-13 05:53 UTC, mortenengen commented on structuralcodes/sections/_generic.py
> +                gp.mass += geo.area * geo.density * 1e-8
L125 and L132, should it be 1e-9?

2024-06-13 09:47 UTC, mortenengen commented on structuralcodes/sections/_generic.py
> +        def compute_area_moments(geometry, material=None):
This is smart 😃

2024-06-13 09:48 UTC, mortenengen requested changes
Very good implementation 😃 just a couple of fixes that should be considered before merging.

2024-06-13 18:39 UTC, talledodiego reviewed
Done everything you mentioned, thanks for the careful review!

2024-06-14 05:43 UTC, mortenengen approved these changes

2024-06-14 05:44 UTC, merged