bugfix marin coefficients
fib-international/structuralcodes pull request #133
Opened 2024-08-07 20:08 UTC by talledodiego

Fixed a bug in parabola-rectangle constitutive law function for evaluation of Marin coefficients. The computation of the coefficients assumed the exponent of the parabolic part is equal to 2. If the exponent is different than 2, the marin method for all constitutive laws (even if less efficient) is called.

2024-08-07 20:15 UTC, mortenengen requested changes
Good fix 👍  could you please add a test that covers this line?

2024-08-08 06:15 UTC, talledodiego commented
> Good fix 👍 could you please add a test that covers this line?

Sure! Done in 374d9552831647aeae97d53ec932af78ee32a525

2024-08-08 06:37 UTC, mortenengen commented
Thanks for covering the line and also fixing the minor bugs. The bigger picture also looks cleaner now 😃 

About the warning. When do we encounter such a situation? Isn't this the parabolic branch of the parabolic rectangular law, which ends at `eps = eps_0`? Could it be that we are not encountering negative numbers, but something close to zero?

2024-08-08 06:45 UTC, talledodiego commented
Thanks!  think I got the small inconsistency! You pointed me to the right direction that I was stupidly not seeing!

2024-08-08 10:56 UTC, mortenengen approved these changes
Good job!

2024-08-08 10:56 UTC, merged